language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'

before_script:
  - composer install --no-interaction

script:
  - composer coverage
  - composer analyse

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
